#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/nelson-black-small.svg"
# use `x` with logo_width, example: "100x"
logo_width = "140x"
# logo text will only show when logo is missing.
logo_text = "Nelson"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png"                # this image will be used as fallback if a page has no image of its own


# Alt colors - bluey 51b9a3 reddy e44944

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# copyright
copyright = "nelson 2022"

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""

# buy premium popup
buy_premium_popup = false

# Main Sections
mainSections = ["blog"]

# reading time for blog posts
reading_time = true

# contact information
[contact_info]
address = "116 S Jamesport Ave, South Jamesport, NY 11970"
phone = ["+1 347 843 3248", "+1 347 843 3248", "+1 347 843 3248"]
email = ["info@nelson.management", "service@nelson.management", "help@nelson.management"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Book A Demo"
link = "https://nelson.management/"

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Get Nelson for your Property"
content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Book A Demo"
button_link = "https://nelson.management/"

############################# social site ########################
[[social]]
title = "Nelson"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "NelsonTweet"
icon = "lab la-twitter"  # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "NelsonIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "NelsonPin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"
